### ISSUE TITLE
Crash with Thaumic Additions

### ISSUE THREAD

**Issue by reddvilzz** [Rebirth-of-the-Night/Quark#11]
Using Quark RotN - r1.6-186
and Thaumic Additions - Reconstructed - 122.7.8

Having crash when launched, here is the [crashlog](https://github.com/Rebirth-of-the-Night/Quark/files/9174974/crash-2022-07-24_08.59.31-client.txt)

**Comment by democat3457** [comment]
Use r1.6-187, 186 has a fatal crash

**Comment by reddvilzz** [comment]
oh it just released. Thanks.
