### ISSUE TITLE
Reacharound placing Feature Not Working

### ISSUE THREAD

**Issue by reddvilzz** [Rebirth-of-the-Night/Quark#12]
Hi again, currently the feature is not working? I have tested the older version 184 and the newest 187 with only Quark as the mod.

Does the behavior changed? Because I've also tested with the original Quark and it works just fine.

**Comment by reddvilzz** [comment]
bump

**Comment by democat3457** [comment]
Oops forgot about this, currently busy with work and getting back to school. Will look when I can, which is hopefully soon :)

**Comment by reddvilzz** [comment]
Okay no worries. Thank you!

**Comment by Krutoy242** [comment]
Have the same proble, Reacharound not working.
Tried to disable and enable option, no change.

**Comment by 2302479492** [comment]
https://github.com/Rebirth-of-the-Night/Quark/blob/ad7e3d7d5148c8c42a6dc4e064313939f3aa4450/src/main/java/vazkii/quark/misc/feature/ReacharoundPlacing.java#L122
Requires "nolavabuild"

**Comment by Krutoy242** [comment]
I need to install this mod to reach around working again?

**Comment by 2302479492** [comment]
> I need to install this mod to reach around working again?

yes,
https://www.curseforge.com/minecraft/mc-mods/cannot-build-over-lava-source-blocks/files
