### ISSUE TITLE
Quark crashes on world generation.

### ISSUE THREAD

**Issue by toErIpNid** [Rebirth-of-the-Night/Quark#6]
Crash log: https://pastebin.com/qm9CXN7L

Regular Log: https://pastebin.com/LG7MJvrj (couldn't paste the whole thing due to it being too big.)

Quark ROTN Version: 1.6-182

**Comment by toErIpNid** [comment]
It seems to only crash on worldgen when "allow cheats" is enabled during world creation for a survival world.

**Comment by democat3457** [comment]
My guess is that one of the other mods sends an unsupported character or a null line in chat when generating a world with cheats. Trying it with a clean install does not produce this crash.
